<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-TU5HT4T" failures="1" tests="12" name="Test" time="0.069" errors="0" timestamp="05 Aug 2023 13:05:16 GMT">
  <testcase classname="org.Example.B" name="Tc012" time="0.007"/>
  <testcase classname="org.Example.C" name="Tc0222" time="0.01"/>
  <testcase classname="org.Example.B" name="Tc032" time="0.001"/>
  <testcase classname="org.Example.C" name="Tc0322" time="0.002"/>
  <testcase classname="org.Example.A" name="Tc01" time="0.018">
    <skipped/>
  </testcase> <!-- Tc01 -->
  <testcase classname="org.Example.A" name="Tc01" time="0.001">
    <skipped/>
  </testcase> <!-- Tc01 -->
  <testcase classname="org.Example.A" name="Tc01" time="0.001">
    <skipped/>
  </testcase> <!-- Tc01 -->
  <testcase classname="org.Example.A" name="Tc01" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Enter Correct name expected [Kasyal] but found [Logesh]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Enter Correct name expected [Kasyal] but found [Logesh]
at org.Example.A.Tc01(A.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 9 stack frames]]>
    </failure>
  </testcase> <!-- Tc01 -->
  <testcase classname="org.Example.A" name="Tc02" time="0.004"/>
  <testcase classname="org.Example.A" name="Tc02" time="0.001"/>
  <testcase classname="org.Example.A" name="Tc02" time="0.0"/>
  <testcase classname="org.Example.A" name="Tc03" time="0.001"/>
  <testcase classname="org.Example.B" name="Tc022" time="0.0">
    <ignored/>
  </testcase> <!-- Tc022 -->
  <testcase classname="org.Example.C" name="Tc0122" time="0.0">
    <ignored/>
  </testcase> <!-- Tc0122 -->
</testsuite> <!-- Test -->
